spring.config.import=optional:application-secret.properties

spring.application.name=${APP_NAME}

spring.datasource.driver-class-name=${DB_DRIVER}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL}

spring.data.rest.base-path=${REST_BASE_PATH}